### ISSUE TITLE
Minor concern on Usage guide prompted during invalid script execution

### ISSUE THREAD

**Issue by Vishanth** [wso2/dockerfiles#12]
For example, when we run the build script with invalid flag values, then the following is prompted. 
echo "Ex: ./build.sh -v 1.9.1 -i 1.0.0 -l 'default|worker|manager'"

This could be misleading for some products, where some products don't have worker or manager profiles. 

Also another concern is for all the flags '-v' '-i' '-l', we are passing certain values. Whereas for '-q' quiet mode, we are not passing any values with the flag, that also should be specified to the user in some manner.

**Comment by chamilad** [comment]
This is a valid concern. We could address this with a certain limit. 

If we set the lists of profiles and versions available in the product build.sh scripts, the common script can display them in the usage. Another option is to look for the available data in the PUPPET_HOME. Let me work with this for a moment.

**Comment by chamilad** [comment]
The scripts now show helpful information in the usage section.

- `build.sh` shows the available product versions and profiles if `PUPPET_HOME` is set
- `run.sh` and `save.sh` show the list of product images already built
- `scp.sh` shows the list of tarballs in the save location `~/docker/images`

**Comment by Vishanth** [comment]
Great work @chamilad.
