### ISSUE TITLE
Distributions do not have a root folder

### ISSUE THREAD

**Issue by imesh** [wso2/dockerfiles#13]
It looks like dockerfile distributions get extracted to the current folder without having a root folder:

~/dev/wso2/dockerfiles/wso2am/target$ unzip wso2am-dockerfile-1.0.0.zip
Archive:  wso2am-dockerfile-1.0.0.zip
  inflating: LICENSE
  inflating: README.md
   creating: wso2am/
  inflating: wso2am/build.sh
  inflating: wso2am/Dockerfile
  inflating: wso2am/README.md
  inflating: wso2am/run.sh
  inflating: wso2am/save.sh
  inflating: wso2am/scp.sh

**Comment by Vishanth** [comment]
Fixed in ec2ae251b43d2951b7fe57dce951f9ab3e2b88b4
