### ISSUE TITLE
build.sh is not working on debian

### ISSUE THREAD

**Issue by imesh** [wso2/dockerfiles#15]
I see the below error when running wso2esb build.sh on a debian 8.3 machine:

root@instance-1:/home/imesh/dockerfiles/wso2esb# ./build.sh -v 4.9.0 -i 1.0.0
flag provided but not defined: --format
See 'docker version --help'.

IMO it would be better to add debug/trace option to see at which point the script fails. Otherwise it is time consuming to debug issues related to bash scripts.
Thanks

**Comment by imesh** [comment]
The problem was with the Docker version, upgraded it to 1.10.3 and the problem got resolved. Thanks!

**Comment by chamilad** [comment]
It might be safer to use "docker version | grep 'Version:' | awk '{print $2}'" instead of the existing command.

**Comment by chamilad** [comment]
Fixed with commit d499a491b6f3497b4b0f59eaa3f9019ef0a1e2ae
