### ISSUE TITLE
JDK 1.8 needs different memory size parameters

### ISSUE THREAD

**Issue by gordillo-ramon** [wso2/dockerfiles#19]
Hi.

When using JDK 1.8, different memory parameters should be used. According with http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6964458, no more -XX:MaxPermSize is in use, but the new -XX:MaxMetaspaceSize. Apart from the parameter, different calculation should be used (permgen was part of the heap, whereas metaspace not).

If not parameterized correctly, kubernetes kills the container when it exceeds the memory reserved for the pod (OOMKiller).

**Comment by imesh** [comment]
Thanks @gordillo-ramon for raising this. I do not think we have defined any memory parameters in Dockerfiles repository. May be it's there in the puppet modules. Can you please point to the exact file?

**Comment by gordillo-ramon** [comment]
True. It is in puppet modules. I will close this issue, and open the corresponding one in that project.
