### ISSUE TITLE
Improve container size

### ISSUE THREAD

**Issue by gordillo-ramon** [wso2/dockerfiles#3]
Some installation files (jdk, wso2 package) are added to the container, and then installed in different steps.

That makes the size almost twice bigger. Example:

```
[developer@wso2sandbox]$ docker history wso2/am-1.10.0:1.0.0
IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
...
3e00ff40662f        About a minute ago   /bin/sh -c puppet apply -e "include ${WSO2_SE   896.4 MB        
...
73f5185743d1        4 minutes ago        /bin/sh -c #(nop) COPY dir:3b98d19970037f581d   581.4 MB            
...
```

Is it possible to set up something like an http_server, and run in the same command download/install/remove? With that approach, the installation files will not be persisted in the layer.

**Comment by imesh** [comment]
A very good suggestion @gordillo-ramon! Will investigate this and get back soon!
Thanks

**Comment by chamilad** [comment]
Thanks for this insight @gordillo-ramon! I tested this scenario with a quick python server and refactoring of the base image instructions to the product images. The result was an almost 600MB reduction in size. I will post the details soon.

**Comment by gordillo-ramon** [comment]
Impresive. Looking forward to test the new version when you commit it!

**Comment by gordillo-ramon** [comment]
Tested. Great!
