### ISSUE TITLE
A folder path needs to be corrected in root REAMD.md file

### ISSUE THREAD

**Issue by imesh** [wso2/dockerfiles#31]
The following typo found in 1.0.0-rc3:

Add product packs and dependencies
- Download the necessary product packs and copy them to <DOCKERFILES_HOME>/common/provision/default/files directory. For example, for WSO2 API Manager 1.9.1 download the product pack and copy the zip file to <DOCKERFILES_HOME>**/common/scripts/provision/default/files**.

**Comment by chamilad** [comment]
Fixed with f49f90e3c72727ceb932af05da7ce3bf97646afa
