### ISSUE TITLE
Allow Kubernetes secrets API based use of SecureVault password

### ISSUE THREAD

**Issue by chamilad** [wso2/dockerfiles#32]
Kubernetes Secrets API allows to pass sensitive data to a pod, one of the options being secret files[1]. It would be better to provide an option to use this data from the files in the `entrypoint.sh` to create the `password-tmp` file.

[1] - http://kubernetes.io/docs/user-guide/secrets/#using-secrets-as-files-from-a-pod

**Comment by ravihansa3000** [comment]
Added in #2

**Comment by ravihansa3000** [comment]
Fixed in #2
