### ISSUE TITLE
It might be better to remove CARBON-HOME from the volume mount path

### ISSUE THREAD

**Issue by imesh** [wso2/dockerfiles#42]
Currentlyt the volume mount path is set to /mnt/wso2/carbon-home in WSO2 Docker images. IMO carbon-home should not be used as a folder name rather it should be used as a reference to the carbon home folder path.  It would be better to use something similar to below:

/mnt/wso2 OR /usr/local/wso2

Please refer how Tomcat has used catalina-home below:

CATALINA_HOME:   /usr/local/tomcat
https://hub.docker.com/_/tomcat/

**Comment by isurulucky** [comment]
The mount path was set to /mnt/wso2/carbon-home to intentionally. IMHO its more intuitive since its possible to replace anything under the carbon product home. Also the the actual carbon product home is denoted by 'CARBON_HOME', so there is no confusion IMHO.

**Comment by ravihansa3000** [comment]
Fixed in fe99bf17fc1c148151b7a313aaa56ac2eb8d55ea 
/mnt/wso2/carbon-home is deprecated, will be removed in a future release
