### ISSUE TITLE
Support debug mode 

### ISSUE THREAD

**Issue by lakwarus** [wso2/dockerfiles#47]
Say I want run our server  in debug mode.  Shall we support that? Say if I pass env DEBUG=TRUE and DEBUG-PORT=5000, then shall we start server in debug mode? This is very useful for developer.
 
We only need to update our init.sh

**Comment by imesh** [comment]
+1 for the idea Lakmal, this would be a useful feature! Will add this in the next release.

**Comment by ravihansa3000** [comment]
Now you can use STARTUP_ARGS to pass any system property to the JVM.

Fixed in https://github.com/wso2/dockerfiles/commit/9ecfde4346e48396f0a02fcde8c0b23f543f05de#diff-0bceb9617515503388a7238f174a0d3cR115
