### ISSUE TITLE
Adding the optionally provided "platform" in the image name

### ISSUE THREAD

**Issue by chamilad** [wso2/dockerfiles#48]
When building an image, if a `platform` is provided by `-s` flag, it should be included in the image name to distinguish the resulting image from images that were built for the same product and version for other platforms.

Ex: 
1. `wso2am:1.10.0` - Generic Docker image 
2. `wso2am-kubernetes:1.10.0` - Docker image to be run on Kubernetes
3. `wso2am-mesos:1.10.0` - Docker image to be run on Mesos

**Comment by pubudu538** [comment]
Fixed with commit id - 265afd17c203b8984584b985d3fa039e5df3a23f
