### ISSUE TITLE
Add a Docker Compose configuration file

### ISSUE THREAD

**Issue by sandrokeil** [wso2/dockerfiles#56]
It would be awesome to have a [Docker Compose configuration](https://docs.docker.com/compose/overview/) file in this repo, which builds and start/stop the services. Any plans for this?

**Comment by swgkg** [comment]
You can use these docker images here to do the Docker Compose based deployment. Please refer this article[1] which I did by using these docker images.

[1]http://gayangunarathne.blogspot.com/2016/06/docker-compose-with-wso2-api-manager.html

**Comment by imesh** [comment]
A great thought @sandrokeil! We are currently working on preparing Docker Compose configurations for deploying WSO2 middleware on Docker with multiple deployment patterns. We will be publishing them soon.
