### ISSUE TITLE
Exported ports does not match the ones in configuration

### ISSUE THREAD

**Issue by gordillo-ramon** [wso2/dockerfiles#6]
From netstat inside the container:

<pre>
root@73c280d0b100:/etc/puppet# netstat -an |more
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:8280            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:51064           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:10397         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:9443            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:<b>9763</b>            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:11111           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:39880           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8243            0.0.0.0:*               LISTEN     
tcp        0      0 172.17.0.2:10711        0.0.0.0:*               LISTEN     
tcp        0      0 172.17.0.2:42719        172.17.0.1:5865         TIME_WAIT  
tcp        0      0 172.17.0.2:50168        172.17.0.2:11111        TIME_WAIT  
tcp        0      0 172.17.0.2:42717        172.17.0.1:5865         TIME_WAIT  
udp        0      0 0.0.0.0:42434           0.0.0.0:*                          
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         STREAM     CONNECTED     1490631  
unix  2      [ ]         STREAM     CONNECTED     1488474  
</pre>

From /mnt/172.17.0.2/wso2am-1.10.0/repository/conf/api-manager.xml:

<pre>
          <URL>https://am.wso2.com:<b>32004</b>/store</URL>
          <URL>https://am.wso2.com:<b>32004</b>/publisher</URL>
</pre>

And docker mapping:

<pre>
[developer@komarr wso2am]$ docker ps --no-trunc
CONTAINER ID                                                       IMAGE                  COMMAND                               CREATED             STATUS              PORTS                                                                                                                                                   NAMES
73c280d0b1008739554a17e41e5e466962c583d05024997a3f8e7780daebd51b   wso2/am-1.10.0:1.0.0   "/bin/sh -c /usr/local/bin/init.sh"   About an hour ago   Up About an hour    0.0.0.0:32773->7711/tcp, 0.0.0.0:32772->8243/tcp, 0.0.0.0:32771->8280/tcp, 0.0.0.0:32770->9443/tcp, 0.0.0.0:<b>32769->9763</b>/tcp, 0.0.0.0:32768->10397/tcp   wso2am-default
</pre>

**Comment by imesh** [comment]
Thanks @gordillo-ramon for reporting this! Yes it looks like Thrift receiver in Key Manager is starting at port 10397, I will fix this in the Dockerfile:

    [2016-03-11 20:27:42,046]  INFO - APIKeyMgtServiceComponent Started thrift key mgt service at port:10397

I only noticed this problem, did you see any other issues?

**Comment by imesh** [comment]
Fixed with commit https://github.com/wso2/dockerfiles/commit/75c598c7ec1fa2316f0230227be60d95cde4e279

**Comment by gordillo-ramon** [comment]
The main problem I had was with port redirection to publisher login. It took me to port 32004, whereas the exposed one was 32769.

**Comment by sajhak** [comment]
@gordillo-ramon, those port settings are configured in hieradata, https://github.com/wso2/puppet-modules/blob/master/hieradata/dev/wso2/wso2am/1.10.0/default.yaml#L79-L82, this is how those ports are set in api-manager.xml.
I believe you have used run.sh to start the container, there we have used -P flag for automatic port publishing, we are planning to update run.sh to expose ports accordingly, for eg
   docker run -p 32004:9443 -p 32003:9763.. etc

**Comment by imesh** [comment]
Yes @sajhak that's the problem, we might need to use the same ports defined in hieradata otherwise proxy ports would not work properly.

**Comment by gordillo-ramon** [comment]
That's the point. The automatic random exposition only works when the port is not referenced any place in the code. Otherwise, like in this case, it should be a particular number.

**Comment by gordillo-ramon** [comment]
Fixed with new docker-run.sh support parameters.
