### ISSUE TITLE
Unable to restart containers

### ISSUE THREAD

**Issue by dannykruitbosch** [wso2/dockerfiles#60]
Hi,

When restarting (or do a stop/start) a container it fails to start up again with the following error:
```
Moving carbon server from /mnt/wso2is-5.1.0 to /mnt/172.17.0.2...
mv: cannot stat '/mnt/wso2is-5.1.0': No such file or directory
```

(Tried this with wso2is):
- Created the image as described in the docs
- `run.sh -v5.1.0 -m /home/danny/wso2/is`
- `docker restart wso2is-default`

I'd like to be able to restart a container without recreating the container over and over again.

Thanks,

Danny

**Comment by imesh** [comment]
Hi Daniel, this is already fixed in master branch. We do not move the distribution any more, instead we use a symlink. Can you please try this on the master branch? Thanks

**Comment by dannykruitbosch** [comment]
Tried and it's solved in master. So thanks!

Danny
