### ISSUE TITLE
Trying to build wso2am stuck in home dir creation

### ISSUE THREAD

**Issue by memorais** [wso2/dockerfiles#64]
I'm using the following document to build an Docker image for wso2am:

https://docs.wso2.com/display/DF120/Building+Docker+Images

But the process seems to be stuck in home directory creation as described:
xsun@tecmmorais:~/Docker/wso2-dockerfiles-1.2.0/wso2am$ ./build.sh -v 2.0.0
Provisioning Method: default
Creating Dockerfile context...
bash: connect: Conexão recusada
bash: /dev/tcp/172.17.0.1/8000: Conexão recusada
Port 8000 was selected for the http server
Starting HTTP server [Doc Root] /home/xsun/Docker/wso2-dockerfiles-1.2.0/common/provision/default/files, [URL] http://172.17.0.1:8000
Serving HTTP on 0.0.0.0 port 8000 ...
172.22.30.244 - - [14/Dec/2016 17:21:53] "GET / HTTP/1.1" 200 -
HTTP server started successfully on http://172.17.0.1:8000
Building docker image wso2am:2.0.0...
Sending build context to Docker daemon  21.5 kB
Step 1 : FROM wso2/wso2base:latest
 ---> 03b324ed733e
Step 2 : MAINTAINER dev@wso2.org
 ---> Running in 59c012998f92
 ---> fb375dc19a4b
Removing intermediate container 59c012998f92
Step 3 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 11d149653611
 ---> 71442fa390ce
Removing intermediate container 11d149653611
Step 4 : ARG WSO2_SERVER
 ---> Running in 1166160357ed
 ---> e26de3dce3a8
Removing intermediate container 1166160357ed
Step 5 : ARG WSO2_SERVER_VERSION
 ---> Running in 2709c7111f93
 ---> 1e17a54889fe
Removing intermediate container 2709c7111f93
Step 6 : ARG WSO2_SERVER_PROFILE
 ---> Running in 9d534de874dc
 ---> a2aaec6015a0
Removing intermediate container 9d534de874dc
Step 7 : ARG WSO2_ENVIRONMENT
 ---> Running in 2d57de746fd0
 ---> b98e6f388f6b
Removing intermediate container 2d57de746fd0
Step 8 : ARG HTTP_PACK_SERVER
 ---> Running in f369e367c554
 ---> dd76618fe7b3
Removing intermediate container f369e367c554
Step 9 : ARG PLATFORM
 ---> Running in 21f20bc84ac9
 ---> fd257c61de9a
Removing intermediate container 21f20bc84ac9
Step 10 : ENV WSO2_SERVER ${WSO2_SERVER:-wso2am} WSO2_SERVER_VERSION ${WSO2_SERVER_VERSION:-1.9.1} WSO2_SERVER_PROFILE ${WSO2_SERVER_PROFILE:-default} WSO2_ENVIRONMENT ${WSO2_ENVIRONMENT:-dev} HTTP_PACK_SERVER ${HTTP_PACK_SERVER} PLATFORM ${PLATFORM}
 ---> Running in d529f077f088
 ---> 2286c520d9fb
Removing intermediate container d529f077f088
Step 11 : COPY scripts/*.sh /usr/local/bin/
 ---> d2628e84adf0
Removing intermediate container 25810f72ca1f
Step 12 : RUN bash /usr/local/bin/image-config.sh
 ---> Running in 3f74d1c30570
Adding group `wso2' (GID 1000) ...
Done.
Adding system user `wso2user' (UID 106) ...
Adding new user `wso2user' (UID 106) with group `wso2' ...
Creating home directory `/home/wso2user' ...

Am I missing some point or this is a possible bug?

**Comment by memorais** [comment]
Ok, after a while the following error is displayed:

Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
Err:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
Err:3 http://archive.ubuntu.com/ubuntu xenial-security InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
iproute2 is already the newest version (4.3.0-1ubuntu3).
unzip is already the newest version (6.0-20ubuntu1).
wget is already the newest version (1.17.1-1ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
172.17.0.2 - - [14/Dec/2016 17:30:17] "GET / HTTP/1.1" 200 -
2016-12-14 19:30:17 URL:http://172.17.0.1:8000/ [370/370] -> "index.html" [1]
172.17.0.2 - - [14/Dec/2016 17:30:17] "GET /jdk-7u79-linux-x64.tar.gz HTTP/1.1" 200 -
2016-12-14 19:30:17 URL:http://172.17.0.1:8000/jdk-7u79-linux-x64.tar.gz [153512879/153512879] -> "jdk-7u79-linux-x64.tar.gz" [1]
172.17.0.2 - - [14/Dec/2016 17:30:17] "GET /jdk-7u80-linux-x64.tar.gz HTTP/1.1" 200 -
2016-12-14 19:30:17 URL:http://172.17.0.1:8000/jdk-7u80-linux-x64.tar.gz [153530841/153530841] -> "jdk-7u80-linux-x64.tar.gz" [1]
FINISHED --2016-12-14 19:30:17--
Total wall clock time: 0.3s
Downloaded: 3 files, 293M in 0.3s (1.03 GB/s)
172.17.0.2 - - [14/Dec/2016 17:30:17] "GET /wso2am-2.0.0.zip HTTP/1.1" 200 -
unpacking wso2am-2.0.0.zip to /mnt
2016-12-14 19:30:18 URL:http://172.17.0.1:8000/wso2am-2.0.0.zip [440118577/440118577] -> "wso2am-2.0.0.zip" [1]
unpacking the JDK to /mnt/jdk-7u80
tar: /mnt/jdk-7u80-linux-x64.tar.gz: Not found in archive
tar: Exiting with failure status due to previous errors

Maybe this is related to DNS which cannot resolve IPv6 addresses...

**Comment by memorais** [comment]
Even with DNS resolving IPv6 I was able to build the docker images successfully, so I'm closing this.

**Comment by chamilad** [comment]
I've experienced DNS issues from time to time, and was mostly successful pointing the host's resolv.conf to `8.8.8.8`.
