### ISSUE TITLE
Might need to check the Docker version and print the Docker version compatibility message

### ISSUE THREAD

**Issue by imesh** [wso2/dockerfiles#8]
At the moment I'm seeing Docker version compatibility message and it seems to be misleading. We might need to do a version comparison and only print this message as an error if the available Docker version is not supported.

    >~/dev/wso2/dockerfiles/wso2am$ ./build.sh -v 1.9.1 -i 1.0.0 default
    PUPPET_HOME is set to ~/dev/wso2/puppet/puppet-modules.
    Docker version should be equal to or later than 1.9.0 to build WSO2 Docker images. Found 1.9.1

[docker-build.sh] (https://github.com/wso2/dockerfiles/blob/master/common/scripts/docker-build.sh#L147)

    docker_version=$(docker version --format '{{.Server.Version}}')
    echoBold "Docker version should be equal to or later than 1.9.0 to build WSO2 Docker images. Found ${docker_version}"
    echo
Thanks

**Comment by Thanu** [comment]
@imesh I have fixed this in this p/r 10 [https://github.com/wso2/dockerfiles/pull/10]. Please review and merge.
Thanks.

**Comment by Thanu** [comment]
Fixed in commit 3c92a004edfbb81013d3eb82ef3a424d90b3b5ee.
